allow the vxlan id to be configured
juju-solutions/charm-flannel pull request #67
Opened 2021-01-14 11:01 UTC by damoxc

In order for flannel to interop with the Windows version the vxlan id and
port need to be configured to 4096 and 4789 respectively[0]. This is done
by adding 2 new configuration parameters and adding them into the
configuration stored in etcd if the config options are present.

[0] https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/#configuring-flannel

2021-02-25 17:43 UTC, Cynerva requested changes
Could you change the [decorator for reconfigure_network](https://github.com/charmed-kubernetes/charm-flannel/blob/6401d2cdb384382e09a6add768bfdbbf585fe6f5/reactive/flannel.py#L210) to be:
```python
@when_any('config.changed.cidr', 'config.changed.port', 'config.changed.vni')
```

That's needed to ensure that if the user changes the port or vni configs after deployment, the charm will update the flannel network config properly.

2021-02-25 17:48 UTC, damoxc commented
@Cynerva added the additional flags

2021-02-26 20:02 UTC, Cynerva requested changes

2021-02-26 20:02 UTC, Cynerva commented on reactive/flannel.py
> +@when('config.changed.cidr', 'config.changed.port', 'config.changed.vni')
This needs to be `@when_any`, not `@when`. As it is now, it will only trigger if *all* of the configs are changed at the same time.

2021-03-01 14:56 UTC, Cynerva commented
Thanks. LGTM

2021-03-01 14:56 UTC, merged